export const stripHotels = [
  "Aria",
  "Bellagio",
  "Caesars Palace",
  "The Cosmopolitan",
  "Encore",
  "The Fontainebleau",
  "Luxor",
  "Mandalay Bay",
  "MGM Grand",
  "New York-New York",
  "Paris Las Vegas",
  "Park MGM",
  "Planet Hollywood",
  "Resorts World",
  "The Venetian",
  "The Palazzo",
  "Wynn",
  "Waldorf Astoria",
  "Vdara",
  "The Linq",
  "Flamingo",
  "Horseshoe",
  "Harrah's",
  "The STRAT",
  "Circa",
  "Downtown Grand",
  "Off-Strip hotel",
  "Airbnb / residence",
] as const;
